version: '3.3'

services:
   db:
     image: mysql:5.7
     restart: always
     volumes:
       - ./db-entrypoint:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
    #  image: wordpress:latest
     image: wp56-xdebug
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       # - ./wpdata:/var/www/html
volumes:
    db_data: {}
